### ISSUE TITLE
Some missing files in the demo folder.

### ISSUE THREAD

**Issue by hikarino-my** [ejp-lab/EJPLab_Computational_Projects#1]
Hi.
I'm very interested in using the SRS2020.
I've checked the demo folder and in the README.md it seems to have two google drive links, though [the former link](https://bit.ly/3frW4Dj) seems to be empty and [the latter link](https://bit.ly/2Qv5iEq) lacks the Jupyter web app file (which seems be named SRS2020ddGPredictor.ipynb).

I also want to know how to use the models in the models folder.
Guessing from the length of the feature importances array,
```py
gbt_model = pickle.load(open('./Models/Full_Dataset_Relaxed_Beta16_Min_Model.sav', 'rb'))
len(gbt_model.feature_importances_) # => 101
```
these features seems to be listed in the Table S5 of the paper.
Is it right to assign these features to the model in the order shown in the table?

**Comment by ejp-lab** [comment]
https://bit.ly/2SAlwNK is the link to the relax. The predictor app binary is found in run_SRS2020_ddG_Predictor_App. We will do some checks to see it is functioning soon.

**Comment by hikarino-my** [comment]
@ejp-lab It seems the updated link to the relax needs access authentication.
I'd like you to check the sharing settings.

**Comment by ejp-lab** [comment]
Corrected. Let me know if it works

**Comment by hikarino-my** [comment]
Thanks it works :)
